language: node_js

node_js:
- lts/carbon
- lts/dubnium
- lts/erbium
- node

env:
- KOA_VERSION=1
- KOA_VERSION=2

before_script:
  - npm remove koa
  - npm install koa@$KOA_VERSION
script: npm run travis
